version: "3.3"

services:
  fia_get:
    build:
      context: /home/rom/apps/fiagetapi/
    container_name: fiagetapi
    restart: always
    user: 1000:985
    volumes:
      - /home/rom/apps/fiagetapi/:/home/fia/fia/fiagetapi
    command: sh -c "/home/fia/pyvenv/bin/python3 /home/fia/fia/fiagetapi/main.py"

