version: "3.9"

services:
  racepagebotdb:
    image: postgres:16-alpine
    container_name: racepagebotdb
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  racepagebottg:
    build: .
    image: racepagebottg:latest
    container_name: racepagebottg
    restart: always
    depends_on:
      - racepagebotdb
    volumes:
      - ./data:/app/data
      - ./fastf1_cache:/root/.cache/fastf1
    env_file:
      - .env
    command: ["python", "bot/telegram.py"]

volumes:
  postgresdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './postgresdata'
